stages:
  - remote-state
  - cloudfront

.terraform:
  image: 
    name: hashicorp/terraform:latest
    entrypoint:
      - '/bin/sh'
      - '-c'

remote-state-plan:
  extends: .terraform
  stage: remote-state
  before_script:
    - terraform -chdir=terraform/remote-state-lock init
  script:
    - terraform -chdir=terraform/remote-state-lock plan -out=remote-state-planfile
  artifacts:
    paths:
      - remote-state-planfile
  when: manual

remote-state-apply:
  extends: .terraform
  stage: remote-state
  before_script:
    - terraform -chdir=terraform/remote-state-lock init
  script:
    - terraform -chdir=terraform/remote-state-lock apply -auto-approve planfile
  artifacts:
    paths:
      - remote-state-planfile
  when: manual

remote-state-destroy:
  extends: .terraform
  stage: remote-state
  before_script:
    - terraform -chdir=terraform/remote-state-lock init
  script:
    - terraform -chdir=terraform/remote-state-lock destroy -auto-approve
  when: manual

cloudfront-plan:
  extends: .terraform
  stage: cloudfront
  before_script:
    - terraform -chdir=terraform/cloudfront init
  script:
    - terraform -chdir=terraform/cloudfront plan -out=cloudfront-planfile
  artifacts:
    paths:
      - cloudfront-planfile

cloudfront-apply:
  extends: .terraform
  stage: cloudfront
  before_script:
    - terraform -chdir=terraform/cloudfront init
  script:
    - terraform -chdir=terraform/cloudfront apply -auto-approve cloudfront-planfile
  when: manual

cloudfront-destroy:
  extends: .terraform
  stage: cloudfront
  before_script:
    - terraform -chdir=terraform/cloudfront init
  script:
    - terraform -chdir=terraform/cloudfront destroy -auto-approve
  when: manual
